### ISSUE TITLE
Powershell checksum did not match

### ISSUE THREAD

**Issue by toburke1** [nutanixdev/nutanix-devstation#7]
I have been demoing this for the past couple of weeks without any issues.  This morning went was going to do another demo and ran into this checksum error:

16.14 POWERSHELL_VERSION=7.4.3
140.6 SHA256: 3ae8f3a556fd7e14fecefaacf15f5cfb0afab520b6f1aeae796d2eeafc9b6422
140.9 sha256sum: WARNING: 1 computed checksum did NOT match
140.9 powershell-7.4.3-linux-x64.tar.gz: FAILED
140.9 ERROR: Feature "PowerShell" (ghcr.io/devcontainers/features/powershell) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/powershell for help troubleshooting this error.
------
Dockerfile-with-features:150
--------------------
 149 |     
 150 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=powershell_4,target=/tmp/build-features-src/powershell_4 \
 151 | >>>     cp -ar /tmp/build-features-src/powershell_4 /tmp/dev-container-features \
 152 | >>>  && chmod -R 0755 /tmp/dev-container-features/powershell_4 \
 153 | >>>  && cd /tmp/dev-container-features/powershell_4 \
 154 | >>>  && chmod +x ./devcontainer-features-install.sh \
 155 | >>>  && ./devcontainer-features-install.sh \
 156 | >>>  && rm -rf /tmp/dev-container-features/powershell_4
 157 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/powershell_4 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/powershell_4  && cd /tmp/dev-container-features/powershell_4  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/powershell_4" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/rancher-desktop/rancher-desktop/hp7y1u6cnbjlr2cxocggs0qla
[164984 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/lq/kkstxgns7jj1_c4kgz_6k3fw0000gp/T/devcontainercli/container-features/0.62.0-1719273931229/Dockerfile-with-features -t vsc-tommy-project-315b602de3cf9baad8ed88bf06bc2a6f438152efad7a31eb9ac7b9d7ce2f9151 --target dev_containers_target_stage --build-arg VARIANT=3.12-bookworm --build-arg ANSIBLE_VERSION=9.5.1 --build-arg PACKER_VERSION=1.9.2 --build-arg CALM_DSL_VERSION=master --build-arg KUBECTL_KARBON=true --build-arg NUTANIX_V4_SDK=true --build-arg OPENSHIFT_CLI_VERSION=stable-4.15 --build-arg OPENSHIFT_INSTALL_VERSION=stable-4.15 --build-arg CLUSTERCTL_VERSION=1.7.1 --build-arg K9S_VERSION=0.32.4 --build-arg COOKIECUTTER_VERSION=2.5.0 --build-context dev_containers_feature_content_source=/var/folders/lq/kkstxgns7jj1_c4kgz_6k3fw0000gp/T/devcontainercli/container-features/0.62.0-1719273931229 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/tommy/Documents/Nutanix/Nutanix-Dev-Station/tommy-project/.devcontainer
[164985 ms]     at mtA (/Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:465:1933)
[164985 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[164985 ms]     at async Pm (/Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:464:1841)
[164985 ms]     at async NH (/Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:464:610)
[164985 ms]     at async KtA (/Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:481:3692)
[164985 ms]     at async eB (/Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[164985 ms]     at async hrA (/Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:661:13373)
[164985 ms]     at async lrA (/Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:661:13114)
[164992 ms] Exit code 1
[164995 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/tommy/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/tommy/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-5a5953c8-df25-47e7-b7a6-5090d24870141719273929220 --workspace-folder /Users/tommy/Documents/Nutanix/Nutanix-Dev-Station/tommy-project --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/tommy/Documents/Nutanix/Nutanix-Dev-Station/tommy-project --id-label devcontainer.config_file=/Users/tommy/Documents/Nutanix/Nutanix-Dev-Station/tommy-project/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/tommy/Documents/Nutanix/Nutanix-Dev-Station/tommy-project/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[164995 ms] Exit code 1

**Comment by pipoe2h** [comment]
Hi @toburke1, 

This was an [issue](https://github.com/devcontainers/features/issues/1041) with the PowerShell feature in the upstream project.

This should now be solved.
